config/routes.rb
Pickety::Application.routes.draw do
  resources :bricks do
    resources :relationships
    resources :categorizations
    resources :categorizations
    resources :notes
  end
  
  resources :categories do
    resources :bricks
  end
      

end

app/models/brick.rb
class Brick < ActiveRecord::Base
  
  has_many :relationships, :dependent => :destroy
  has_many :relations, :through => :relationships
  
  has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "relation_id", :dependent => :destroy
  has_many :inverse_relations, :through => :inverse_relationships, :source => :brick
  
  has_many :statizations, :dependent => :destroy
  has_many :states, :through => :statizations
  
  has_many :categorizations, :dependent => :destroy
  has_many :categories, :through => :categorizations
  
  has_many :notes, :as => :notable
    
  validates :name, :presence => true, :uniqueness => true
  
  attr_accessor :new_category, :new_state, :new_species, :new_gender, :brick_category, :brick_to_state, :state_to_species, :species_to_gender, :gender_to_field
  
  after_create :build_nested_objects
  
  private
  
  def build_nested_objects
    use_or_create_state
    use_or_create_species
    use_or_create_gender
    
    field   = self.gender_to_field
    self.statizations.create(:state_id => @state)
    Speciesization.create(:state_id => @state, :species_id => @species)
    Genderization.create(:species_id => @species, :gender_id => @gender)
  end
  
  def use_or_create_state
    if !self.new_state.blank?
      @state = State.create(:name => self.new_state)
      @state = @state.id
    else
      @state = self.brick_to_state
    end
  end
  
  def use_or_create_species
    if !self.new_species.blank?
      @species = Species.create(:name => self.new_species)
      @species = @species.id
    else
      @species = self.state_to_species
    end
  end
  
  def use_or_create_gender
    if !self.new_gender.blank?
      @gender = Gender.create(:name => self.new_gender)
      @gender = @gender.id
    else
      @gender = self.species_to_gender
    end
  end
  
  
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :brick
  belongs_to :category
  
  validates :brick_id, :presence => true, :uniqueness => { :scope => :category_id }
  validates :category_id, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations, :dependent => :destroy
  has_many :categories, :through => :categorizations
  
  validates :name, :presence => true
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :genderizations, :dependent => :destroy
  has_many :species, :through => :genderizations
  
  validates :name, :presence => true, :uniqueness => true
end

app/models/genderization.rb
class Genderization < ActiveRecord::Base
  belongs_to :species
  belongs_to :gender
  
  validates :species_id, :presence => true, :uniqueness => { :scope => :gender_id }
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :notable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :relation, :class_name => 'Brick'
  belongs_to :brick
  
  validates :brick_id, :presence => true, :uniqueness => { :scope => :relation_id }
end

app/models/species.rb
class Species < ActiveRecord::Base
  has_many :speciesizations, :dependent => :destroy
  has_many :states, :through => :speciesizations
  
  has_many :genderizations, :dependent => :destroy
  has_many :genders, :through => :genderizations
  
  validates :name, :presence => true, :uniqueness => true
end

app/models/speciesization.rb
class Speciesization < ActiveRecord::Base
  belongs_to :state
  belongs_to :species
  
  validates :state_id, :presence => true, :uniqueness => { :scope => :species_id }
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :statizations, :dependent => :destroy
  has_many :bricks, :through => :statizations
  
  has_many :speciesizations, :dependent => :destroy
  has_many :species, :through => :speciesizations
  
  validates :name, :presence => true, :uniqueness => true
end

app/models/statization.rb
class Statization < ActiveRecord::Base
  belongs_to :brick
  belongs_to :state
  
  validates :brick_id, :presence => true, :uniqueness => { :scope => :state_id }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bricks_controller.rb
class BricksController < InheritedResources::Base
  belongs_to :category, :optional => true  
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  belongs_to :category, :optional => true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def index
    @notable = find_notable
    @notes = @notable.notes
  end
  
  def show
    @notable = find_notable
    @note = @notable.notes.find(params[:id])
  end
  
  def new
    @notable = find_notable
    @note = @notable.notes.build
  end
  
  def create
    @notable = find_notable
    @note = @notable.notes.build(params[:note])
    if @note.save
      flash[:notice] = "Successfully saved note."
      redirect_to @notable
    else
      render :action => 'new'
    end
  end
  
  private
  
  def find_notable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bricks_helper.rb
module BricksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorizations_helper.rb
module CategorizationsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/bricks/_form.html.erb
<%= form_for @brick do |f| %>
  <%= f.error_messages %>
  <fieldset>
    <legend>Brick Specific</legend>
    <ol>
      <li>
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </li>
      <li>
        <%= f.collection_select :brick_category, Category.all, :id, :name, :prompt => "Select a Category" %> or create a new one:
        <%= f.text_field :new_category %>
      </li>
    </ol>
  </fieldset>

  <fieldset>
    <legend>State Info</legend>
    <ol>
      <li>
        <%= f.collection_select :brick_to_state, State.all, :id, :name, :prompt => "Select a State" %> or create a new one: 
        <%= f.text_field :new_state %>
      </li>
      <li>
        <%= f.collection_select :state_to_species, Species.all, :id, :name, :prompt => "Select a Species" %> or create a new one: 
        <%= f.text_field :new_species %>
      </li>
      <li>
        <%= f.collection_select :species_to_gender, Gender.all, :id, :name, :prompt => "Select a Gender" %> or create a new one: 
        <%= f.text_field :new_gender %>
      </li>
    </ol>
  </fieldset>

  <p><%= f.submit %></p>
<% end %>

<%= session[:brick_params]%>
<%= params[:brick] %>

app/views/bricks/edit.html.erb
<% title "Edit Brick" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @brick %> |
  <%= link_to "View All", bricks_path %>
</p>

app/views/bricks/index.html.erb
<% title "Bricks" %>

<table>
  <tr>
    <th>Brick</th>
    <th>State</th>
    <th>Relation</th>
    <th>Inverse Relation</th>
  </tr>
  
  <% @bricks.each do |brick| %>
    <tr>
      <td><%= link_to brick.name, brick %></td>
      <td>
        <table>
          <% brick.states.each do |state| %>
            <tr>
              <td><%= state.name %></td>
              <td>
                <table>
                  <% state.species.each do |species| %>
                    <tr>
                      <td><%= species.name %></td>
                      <td>
                        <table>
                          <% species.genders.each do |gender| %>
                            <tr>
                              <td><%= gender.name %></td>
                            </tr>
                          <% end %>
                        </table>
                      </td>
                    </tr>
                  <% end %>
                </table>
              </td>
            </tr>
          <% end %>
        </table>
      </td>
      <td>
        <table>
          <% brick.relations.each do |relation| %>
            <tr>
              <td><%= link_to relation.name, relation %></td>
            </tr>
          <% end %>
        </table>
      </td>
      <td>
        <table>
          <% brick.inverse_relations.each do |relation| %>
            <tr>
              <td><%= link_to relation.name, relation %></td>
            </tr>
          <% end %>
        </table>
      </td>
      <td>
        <%= link_to "Destroy #{brick.name}", brick, :method => :delete, :confirm => "Are you sure you want to permanently destroy #{brick.name}? "%>
      </td>
      <td>
        <%= link_to "View/Edit Relationships", brick_relationships_url(brick) %>
      </td>
    </tr>
  <% end %>
</table>
<p><%= link_to "New Brick", new_brick_path %></p>

app/views/bricks/new.html.erb
<% title "New Brick" %>

<%= render 'form' %>

<p><%= link_to "Back to List", bricks_path %></p>

app/views/bricks/show.html.erb
<% title "Brick" %>

<p>
  <strong>Name:</strong>
  <%= @brick.name %>
</p>

<table>
  <tr>
    <th>State</th>
    <th>Species</th>
    <th>Gender</th>
    <th>Field</th>
  </tr>
  
  <% @brick.states.each do |state| %>
    <tr>
      <td>
        <%= state.name %>
      </td>
      <td>
        <table>
          <% state.species.each do |species| %>
            <tr>
              <td><%= species.name %></td>
            </tr>
          <% end %>
        </table>
      </td>
      <td>
        <% state.species.each do |species| %>
          <% species.genders.each do |gender| %>
            <%= gender.name %>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<ul>
  <% @brick.notes.each do |note| %>
    <li><%= link_to note.title, brick_note_url(@brick, note) %></li>
  <% end %>
</ul>

<p>
  <%= link_to "Edit", edit_brick_path(@brick) %> |
  <%= link_to "Destroy", @brick, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", bricks_path %>
</p>

app/views/notes/index.html.erb
<h1>Notes</h1>

<ul>
  <% @notes.each do |note| %>
    <li><%= note.content %></li>
  <% end %>
</ul>

app/views/notes/new.html.erb
<%= form_for [@notable, @note] do |f| %>
  
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  
  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<h1><%= @notable.name %></h1>

<h2>Note: <%= @note.title %></h2>
<%= @note.content %>